const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
    getVaults: () => ipcRenderer.invoke('get-vaults'),
    createVault: (data) => ipcRenderer.invoke('create-vault', data),
    importVault: () => ipcRenderer.invoke('import-vault'),
    openVault: (data) => ipcRenderer.invoke('open-vault', data),
    loadDashboard: () => ipcRenderer.send('load-dashboard'),
    removeVault: (path) => ipcRenderer.invoke('remove-vault', path),
    getData: (tabId) => ipcRenderer.invoke('get-data', tabId),
    addItem: (payload) => ipcRenderer.invoke('add-item', payload),
    updatePassword: (payload) => ipcRenderer.invoke('update-password', payload),
    deletePassword: (id) => ipcRenderer.invoke('delete-password', id),
    manualSave: () => ipcRenderer.invoke('manual-save'),
    getCounts: () => ipcRenderer.invoke('get-counts'),
    getVaultName: () => ipcRenderer.invoke('get-vault-name'),
    getGroups: () => ipcRenderer.invoke('get-groups'),
    addGroup: (name) => ipcRenderer.invoke('add-group', name),
    deleteGroup: (id) => ipcRenderer.invoke('delete-group', id),
    addFileToVault: () => ipcRenderer.invoke('add-file-to-vault'),
    exportFileFromVault: (fileId) => ipcRenderer.invoke('export-file-from-vault', fileId),
    deleteFileFromVault: (fileId) => ipcRenderer.invoke('delete-file-from-vault', fileId),
    getFilesData: () => ipcRenderer.invoke('get-files-data'),
    getFilesCount: () => ipcRenderer.invoke('get-files-count'),
    generateGpgKeypair: (payload) => ipcRenderer.invoke('generate-gpg-keypair', payload),
    importGpgKeyFromFile: () => ipcRenderer.invoke('import-gpg-key-from-file'),
    exportGpgKey: (id) => ipcRenderer.invoke('export-gpg-key', id),
    deleteGpgKey: (id) => ipcRenderer.invoke('delete-gpg-key', id),
    gpgEncrypt: (payload) => ipcRenderer.invoke('gpg-encrypt', payload),
    gpgDecrypt: (payload) => ipcRenderer.invoke('gpg-decrypt', payload),
    getAppInfo: () => ipcRenderer.invoke('get-app-info'),

    // Updates
    checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
    downloadUpdate: () => ipcRenderer.invoke('download-update'),
    quitAndInstall: () => ipcRenderer.invoke('quit-and-install'),
    getUpdateSettings: () => ipcRenderer.invoke('get-update-settings'),
    setUpdateSettings: (settings) => ipcRenderer.invoke('set-update-settings', settings),
    onUpdateAvailable: (callback) => ipcRenderer.on('update-available', (e, info) => callback(info)),
    onUpdateNotAvailable: (callback) => ipcRenderer.on('update-not-available', (e, info) => callback(info)),
    onUpdateDownloaded: (callback) => ipcRenderer.on('update-downloaded', (e, info) => callback(info)),
    onUpdateError: (callback) => ipcRenderer.on('update-error', (e, msg) => callback(msg)),
    onUpdateChecking: (callback) => ipcRenderer.on('update-checking', (e) => callback()),
    onUpdateProgress: (callback) => ipcRenderer.on('update-download-progress', (e, progress) => callback(progress))
});